version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: dispofast-db
    environment:
      POSTGRES_DB: dispofast
      POSTGRES_USER: dispofast
      POSTGRES_PASSWORD: dispofast
    ports:
      - "5433:5432"
    volumes:
      - dispofast_data:/var/lib/postgresql/data

volumes:
  dispofast_data:
