spring:
  datasource:
    url: ${DB_PROTOCOL:jdbc:postgresql}://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:dispofast}
    username: ${DB_USERNAME:dispofast}
    password: ${DB_PASSWORD:dispofast}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true

app:
  jwt:
    secret: ${JWT_SECRET:ihavetochangeThisSecretKeysoon1234567890}
    expirationSeconds: 3600000

logging:
  level:
    com.dispocol.dispofast.modules.iam.infra.security: DEBUG
