spring:
  application:
    name: dispofast
  profiles:
    active: dev
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: ${DB_PROTOCOL}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true

server:
  port: 8080
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info
