spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/dispofast
    username: dispofast
    password: dispofast
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true

app:
  jwt:
    secret: ihavetochangeThisSecretKeysoon1234567890
    expirationSeconds: 3600000

logging:
  level:
    com.dispocol.dispofast.modules.iam.infra.security: DEBUG
