spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/dispofast
    username: dispofast
    password: dispofast
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true

app:
  jwt:
    secret: devSecretKey
    expiration-ms: 3600000
