UPDATE quotes
SET payment_condition = CASE payment_condition
    WHEN 'CONTADO_15_DIAS' THEN 'CREDITO_15_DIAS'
    WHEN 'CONTADO_30_DIAS' THEN 'CREDITO_30_DIAS'
    WHEN 'CONTADO_60_DIAS' THEN 'CREDITO_60_DIAS'
    WHEN 'CONTADO_90_DIAS' THEN 'CREDITO_90_DIAS'
    ELSE payment_condition
END
WHERE payment_condition IN ('CONTADO_15_DIAS', 'CONTADO_30_DIAS', 'CONTADO_60_DIAS', 'CONTADO_90_DIAS');

UPDATE sales_order
SET payment_condition = CASE payment_condition
    WHEN 'CONTADO_15_DIAS' THEN 'CREDITO_15_DIAS'
    WHEN 'CONTADO_30_DIAS' THEN 'CREDITO_30_DIAS'
    WHEN 'CONTADO_60_DIAS' THEN 'CREDITO_60_DIAS'
    WHEN 'CONTADO_90_DIAS' THEN 'CREDITO_90_DIAS'
    ELSE payment_condition
END
WHERE payment_condition IN ('CONTADO_15_DIAS', 'CONTADO_30_DIAS', 'CONTADO_60_DIAS', 'CONTADO_90_DIAS');
