ALTER TABLE shipments
  ADD COLUMN IF NOT EXISTS invoice_number  VARCHAR(50),
  ADD COLUMN IF NOT EXISTS created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS client_name     VARCHAR(255),
  ADD COLUMN IF NOT EXISTS asesor_name     VARCHAR(255);
